{
    baseTheme: null,
    themeName: null,
    routing: false,
    ecmUrl: null,
    ecmTitle: null,
    markersUrl: 'markers.json',
    routesUrl: 'routes.json',
    lan: 'fi',
    initLocation: {
        lat: 60.169872,
        lng: 24.938099
    },
    cardDefaultImg: 'absolute/path/to/themes/default/images/default-img.jpg',
    externalMarkers: null,
    mapDefaultTravelMode: 'WALKING',
    mapInitZoom: 10,
    mapMinZoom: 0,
    mapMaxZoom: 21,
    mapLayers: null,
    mapTypeId: 'terrain',
    mapTypes: [
        'roadmap',
        'satellite',
        'hybrid',
        'terrain'
    ],
    mapRouteMarkersThreshold: 12,
    markerClustererOptions: {
        gridSize: 56,
        zoomOnClick: false,
        minimumClusterSize: 2,
        textColor: 'white',
        textSize: 10,
        width: 32,
        height: 32
    },
    modes: null,
    offsetTop: 'auto',
    offsetTopSel: 'header',
    showBadgeFilters: true,
    showMapFeedToggle: true,
    showModeButtons: true,
    showPrint: false,
    showTagFilters: true,
    showTypeFilters: true,
    tagFiltersIcons: true,
    usePlugin: false,
    userPosInterval: 5000
}
